import fc from 'fast-check'
import { describe, expect, it, vi } from 'vitest'

import { createClient } from '../../src/client.js'
import {
  downloadProgressPlugin,
  type DownloadProgressEvent,
} from '../../src/plugins/download-progress.js'

function streamResponse(
  chunks: Uint8Array[],
  contentLength?: string,
  init: ResponseInit = {}
): Response {
  const body = new ReadableStream<Uint8Array>({
    start(controller) {
      for (const chunk of chunks) controller.enqueue(chunk)
      controller.close()
    },
  })
  const headers = new Headers(init.headers)
  if (contentLength !== undefined) headers.set('content-length', contentLength)
  return new Response(body, { ...init, headers })
}

function concatenate(chunks: Uint8Array[]): Uint8Array {
  const result = new Uint8Array(
    chunks.reduce((total, chunk) => total + chunk.byteLength, 0)
  )
  let offset = 0
  for (const chunk of chunks) {
    result.set(chunk, offset)
    offset += chunk.byteLength
  }
  return result
}

describe('download progress plugin fuzzing', () => {
  it('preserves generated bytes and reports exact cumulative progress', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(fc.uint8Array({ minLength: 1, maxLength: 64 }), {
          minLength: 1,
          maxLength: 20,
        }),
        async (chunks) => {
          const expected = concatenate(chunks)
          const events: Array<{
            progress: DownloadProgressEvent
            chunk: Uint8Array
          }> = []
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [
              downloadProgressPlugin((progress, chunk) => {
                events.push({ progress, chunk: chunk.slice() })
              }),
            ],
            fetchHandler: async () =>
              streamResponse(chunks, String(expected.byteLength)),
          })

          const response = await client('https://example.com/generated-file')
          const received = new Uint8Array(await response.arrayBuffer())

          expect(received).toEqual(expected)
          expect(events).toHaveLength(chunks.length)
          let transferred = 0
          events.forEach(({ progress, chunk }, index) => {
            transferred += chunks[index].byteLength
            expect(chunk).toEqual(chunks[index])
            expect(progress).toEqual({
              transferredBytes: transferred,
              totalBytes: expected.byteLength,
              percent: transferred / expected.byteLength,
            })
          })
          expect(client.pendingRequests).toHaveLength(0)
        }
      ),
      { numRuns: 500 }
    )
  })

  it('normalizes malformed Content-Length instead of reporting invalid numbers', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constantFrom(
          'garbage',
          '-1',
          '1.5',
          '12px',
          'NaN',
          'Infinity',
          '0x10'
        ),
        fc.uint8Array({ minLength: 1, maxLength: 100 }),
        async (contentLength, chunk) => {
          const events: DownloadProgressEvent[] = []
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [
              downloadProgressPlugin((progress) => events.push(progress)),
            ],
            fetchHandler: async () => streamResponse([chunk], contentLength),
          })

          const response = await client('https://example.com/bad-length')
          await response.arrayBuffer()

          expect(events).toHaveLength(1)
          expect(events[0]).toEqual({
            percent: 0,
            transferredBytes: chunk.byteLength,
            totalBytes: 0,
          })
        }
      ),
      { numRuns: 300 }
    )
  })

  it('keeps reported percentages within the documented zero-to-one range', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 100 }),
        fc.integer({ min: 1, max: 100 }),
        async (declaredBytes, extraBytes) => {
          const chunk = new Uint8Array(declaredBytes + extraBytes)
          const percents: number[] = []
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [
              downloadProgressPlugin(({ percent }) => percents.push(percent)),
            ],
            fetchHandler: async () =>
              streamResponse([chunk], String(declaredBytes)),
          })

          const response = await client('https://example.com/short-length')
          await response.arrayBuffer()

          expect(percents).toEqual([1])
        }
      ),
      { numRuns: 300 }
    )
  })

  it('propagates generated upstream stream failures after delivered chunks', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(fc.uint8Array({ minLength: 1, maxLength: 32 }), {
          minLength: 0,
          maxLength: 10,
        }),
        fc.string({ minLength: 1, maxLength: 50 }),
        async (chunks, message) => {
          const failure = new Error(message)
          const events: DownloadProgressEvent[] = []
          const body = new ReadableStream<Uint8Array>({
            start(controller) {
              for (const chunk of chunks) controller.enqueue(chunk)
              controller.error(failure)
            },
          })
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [
              downloadProgressPlugin((progress) => events.push(progress)),
            ],
            fetchHandler: async () => new Response(body),
          })

          const response = await client('https://example.com/broken-stream')
          await expect(response.arrayBuffer()).rejects.toBe(failure)
          expect(events.length).toBeLessThanOrEqual(chunks.length)
          expect(client.pendingRequests).toHaveLength(0)
        }
      ),
      { numRuns: 300 }
    )
  })

  it('turns a throwing progress callback into a readable-stream failure', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(fc.uint8Array({ minLength: 1, maxLength: 32 }), {
          minLength: 1,
          maxLength: 10,
        }),
        fc.integer({ min: 0, max: 9 }),
        async (chunks, generatedIndex) => {
          const throwAt = generatedIndex % chunks.length
          const callbackFailure = new Error('generated progress failure')
          const onProgress = vi.fn(() => {
            if (onProgress.mock.calls.length - 1 === throwAt) {
              throw callbackFailure
            }
          })
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [downloadProgressPlugin(onProgress)],
            fetchHandler: async () => streamResponse(chunks),
          })

          const response = await client('https://example.com/callback-failure')
          await expect(response.arrayBuffer()).rejects.toBe(callbackFailure)
          expect(onProgress).toHaveBeenCalledTimes(throwAt + 1)
          expect(client.pendingRequests).toHaveLength(0)
        }
      ),
      { numRuns: 300 }
    )
  })

  it('preserves generated response metadata while wrapping the body', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc
          .integer({ min: 200, max: 599 })
          .filter((status) => ![204, 205, 304].includes(status)),
        fc.stringMatching(/^[A-Za-z0-9 _-]{0,30}$/),
        fc.stringMatching(/^[A-Za-z0-9_-]{0,30}$/),
        async (status, statusText, headerValue) => {
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [downloadProgressPlugin(() => {})],
            fetchHandler: async () =>
              streamResponse([new Uint8Array([1])], '1', {
                status,
                statusText,
                headers: { 'x-generated': headerValue },
              }),
          })

          const response = await client('https://example.com/metadata')

          expect(response.status).toBe(status)
          expect(response.statusText).toBe(statusText)
          expect(response.headers.get('x-generated')).toBe(headerValue)
          expect(new Uint8Array(await response.arrayBuffer())).toEqual(
            new Uint8Array([1])
          )
        }
      ),
      { numRuns: 300 }
    )
  })

  it('propagates consumer cancellation to the upstream response stream', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.uint8Array({ minLength: 1, maxLength: 100 }),
        fc.string({ maxLength: 50 }),
        async (chunk, reason) => {
          let cancelled = false
          const upstream = new ReadableStream<Uint8Array>({
            start(controller) {
              controller.enqueue(chunk)
            },
            cancel() {
              cancelled = true
            },
          })
          const onProgress = vi.fn()
          const client = createClient({
            timeout: 0,
            retries: 0,
            plugins: [downloadProgressPlugin(onProgress)],
            fetchHandler: async () => new Response(upstream),
          })

          const response = await client('https://example.com/cancel-stream')
          const reader = response.body!.getReader()
          const first = await reader.read()
          await reader.cancel(reason)
          await Promise.resolve()

          expect(first).toEqual({ done: false, value: chunk })
          expect(cancelled).toBe(true)
          expect(onProgress).toHaveBeenCalledOnce()
          expect(client.pendingRequests).toHaveLength(0)
        }
      ),
      { numRuns: 300 }
    )
  })
})
