name: Announce Release on Discord

on:
  push:
    tags:
      - 'v*'

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        run: |
          payload=$(jq -n \
            --arg content "New fetch-kit Release: $GITHUB_REF_NAME" \
            '{content: $content}')
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${{ secrets.DISCORD_WEBHOOK }}"
