name: Announce fetch-kit Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  announce:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract changelog for tag
        id: changelog
        shell: pwsh
        run: |
          $TAG = "${{ github.ref_name }}"             # tag pushed
          $TAG_NO_V = $TAG.TrimStart('v')
          $found = $false

          $lines = Get-Content CHANGELOG.md | ForEach-Object {
              if ($_ -match "^##\s+$TAG" -or $_ -match "^##\s+$TAG_NO_V") {
                  $found = $true
                  return
              }
              if ($found -and $_ -match "^##\s+") {
                  $found = $false
              }
              if ($found) { $_ }
