name: Announce fetch-kit Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Announce to Discord
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          LATEST=$(sed -n "/^## $TAG$/,/^## /{ /^## /!p }" CHANGELOG.md | sed 's/"/\\"/g')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"📦 **New fetch-kit Release: $TAG**\n$LATEST\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
